### ISSUE TITLE
Feature request: Responsive lightbox

### ISSUE THREAD

**Issue by mesiu** [achacttn/photo-viewer#1]
As a user, I'd love to be able to use this app on a variety of devices. 

Currently when some images are too wide, the metadata becomes cropped in some resolutions. 

<img width="1280" alt="Screen Shot 2020-10-12 at 11 57 42 am" src="https://user-images.githubusercontent.com/14955652/95698035-61c22400-0c8c-11eb-9ea8-7f04081664fb.png">

Also on smaller screens, the image needs to be resized.

<img width="498" alt="Screen Shot 2020-10-12 at 11 58 17 am" src="https://user-images.githubusercontent.com/14955652/95698056-70104000-0c8c-11eb-892c-ddcb0a1dd7f0.png">

**Comment by achacttn** [comment]
Hi Mel, thank you for bringing this to my attention.

Some properties have been added, such as ensuring each half has flex-basis of 50%, and the image will retain its aspect ratio with `object-fit: contain`.

The lightbox should now show user the entire image, as well as not spill over into metadata territory.

**Comment by mesiu** [comment]
Thanks Scott, looking much better now :)
