### ISSUE TITLE
Optimisation: Photo list

### ISSUE THREAD

**Issue by mesiu** [achacttn/photo-viewer#2]
As a possible improvement to the image list, images could be fetched from the `/photos` list endpoint. This will enable use of the pagination query parameters thereby removing the need to filter out duplicates when saving state.

**Comment by achacttn** [comment]
Hi,

The endpoint can be changed, and `pageState` could be saved, with `pageState` being incremented every time a request is made (with `per_page` param matched to 30).

On an additional note, `/photos` and `/photos/random` return different objects, so upon going into a lightbox, another request will have to be made to `/photos/:id` to retrieve exif and location data.
